const nk = (book, chapterStart, verseStart, chapterEnd = chapterStart, verseEnd = verseStart) => ({
  translation: "NKRV",
  sourceKey: book,
  book,
  chapterStart,
  verseStart,
  chapterEnd,
  verseEnd,
});

const hb = (book, chapterStart, verseStart, chapterEnd = chapterStart, verseEnd = verseStart) => ({
  translation: "BHS",
  sourceKey: book,
  book,
  chapterStart,
  verseStart,
  chapterEnd,
  verseEnd,
});

const gr = (
  book,
  sourceKey,
  chapterStart,
  verseStart,
  chapterEnd = chapterStart,
  verseEnd = verseStart,
) => ({
  translation: "SBLGNT",
  sourceKey,
  book,
  chapterStart,
  verseStart,
  chapterEnd,
  verseEnd,
});

const he = (lemma, transliteration, glossKo, ...relatedRefs) => ({
  lang: "he",
  lemma,
  transliteration,
  glossKo,
  relatedRefs,
});

const ge = (lemma, transliteration, glossKo, ...relatedRefs) => ({
  lang: "gr",
  lemma,
  transliteration,
  glossKo,
  relatedRefs,
});

export const sourcePaths = {
  nkrv: "/mnt/c/Users/MiniPC/Documents/Obsidian Vault/기본 데이터/역본/NKRV",
  bhs: "/mnt/c/Users/MiniPC/Documents/Obsidian Vault/기본 데이터/역본/BHS",
  sblgnt: "/mnt/c/Users/MiniPC/Documents/Obsidian Vault/기본 데이터/역본/sblgnt",
};

export const eras = [
  {
    id: "E01",
    order: 1,
    name: "창조와 타락",
    rangeLabel: "창세기 1-3",
    summary: "하나님의 창조, 인간의 소명, 그리고 죄로 인한 첫 단절이 동시에 드러나는 시작점.",
    covenantAxis: "창조 질서 · 하나님의 형상 · 원복음",
    themeColor: "#7f321d",
  },
  {
    id: "E02",
    order: 2,
    name: "홍수와 열국 분산",
    rangeLabel: "창세기 4-11",
    summary: "심판과 보존이 반복되며 인류 역사 전체가 언약과 심판의 틀 안에 놓인다.",
    covenantAxis: "보존 언약 · 열방 형성",
    themeColor: "#925224",
  },
  {
    id: "E03",
    order: 3,
    name: "족장과 약속 계보",
    rangeLabel: "창세기 12-50",
    summary: "아브라함에게 주어진 약속이 이삭, 야곱, 요셉을 거치며 한 가족의 역사로 구체화된다.",
    covenantAxis: "아브라함 언약 · 씨 · 땅 · 복",
    themeColor: "#aa7740",
  },
  {
    id: "E04",
    order: 4,
    name: "출애굽과 시내 언약",
    rangeLabel: "출애굽기 1-24",
    summary: "구속 사건과 언약 체결이 결합되며 하나님 백성이 공적 공동체로 세워진다.",
    covenantAxis: "구속 · 유월절 · 시내 언약",
    themeColor: "#6a7845",
  },
  {
    id: "E05",
    order: 5,
    name: "성막, 광야, 언약 갱신",
    rangeLabel: "출애굽기 25-신명기 34",
    summary: "임재, 불순종, 심판, 그리고 다음 세대를 향한 언약 갱신이 광야에서 교차한다.",
    covenantAxis: "임재 · 거룩 · 갱신",
    themeColor: "#477063",
  },
  {
    id: "E06",
    order: 6,
    name: "가나안 진입과 정복",
    rangeLabel: "여호수아",
    summary: "약속의 땅이 실제 역사 공간으로 주어지며 기업과 언약의 언어가 결합한다.",
    covenantAxis: "기업 · 땅 분배 · 순종",
    themeColor: "#2d6672",
  },
  {
    id: "E07",
    order: 7,
    name: "사사 시대와 왕정 전환",
    rangeLabel: "사사기 · 룻기 · 사무엘상 1-10",
    summary: "반복되는 배교와 구원이 왕정 전환의 필요성을 드러내고 사무엘이 경계선에 선다.",
    covenantAxis: "언약 소송 · 왕정 전환",
    themeColor: "#375084",
  },
  {
    id: "E08",
    order: 8,
    name: "통일왕국과 다윗 언약",
    rangeLabel: "사무엘상 11-열왕기상 11 · 역대상 · 역대하 1-9",
    summary: "다윗 왕조와 성전이 결합하며 메시아 기대가 왕적 언약의 형태로 고정된다.",
    covenantAxis: "다윗 언약 · 예루살렘 · 성전",
    themeColor: "#613d80",
  },
  {
    id: "E09",
    order: 9,
    name: "분열왕국과 북왕국 멸망",
    rangeLabel: "열왕기상 12-열왕기하 17 · 역대하 10-28",
    summary: "왕국 분열 이후 선지자 사역과 언약 소송이 본격화되고 북왕국이 먼저 무너진다.",
    covenantAxis: "왕국 분열 · 선지자 · 심판",
    themeColor: "#8d4661",
  },
  {
    id: "E10",
    order: 10,
    name: "유다 말기와 바벨론 포로",
    rangeLabel: "열왕기하 18-25 · 역대하 29-36 · 예레미야 · 에스겔 · 다니엘 · 애가",
    summary: "유다 말기의 개혁과 멸망, 그리고 포로기 회복 약속이 같은 신학적 축 안에 놓인다.",
    covenantAxis: "포로 · 새 언약 약속 · 회복",
    themeColor: "#a64f42",
  },
  {
    id: "E11",
    order: 11,
    name: "귀환과 회복 공동체",
    rangeLabel: "에스라 · 느헤미야 · 에스더 · 학개 · 스가랴 · 말라기",
    summary: "귀환 공동체가 성전과 율법, 공동체 경계선을 다시 세우지만 미완의 긴장을 남긴다.",
    covenantAxis: "귀환 · 재건 · 갱신",
    themeColor: "#87704c",
  },
  {
    id: "E12",
    order: 12,
    name: "중간기 배경",
    rangeLabel: "말라기 이후-복음서 직전",
    summary: "본체 타임라인이 아니라 메시아 도래 전 배경 설명을 위한 부록 구간.",
    covenantAxis: "부록 · 제국 배경",
    themeColor: "#7d7466",
  },
  {
    id: "E13",
    order: 13,
    name: "메시아 도래와 공생애",
    rangeLabel: "사복음서",
    summary: "성육신과 하나님 나라 선포가 구약의 약속을 공생애 한복판에서 가시화한다.",
    covenantAxis: "성육신 · 하나님 나라 · 제자 공동체",
    themeColor: "#9b2f28",
  },
  {
    id: "E14",
    order: 14,
    name: "십자가, 부활, 승천, 오순절",
    rangeLabel: "복음서 후반 · 사도행전 1-2",
    summary: "새 언약이 피로 확정되고 부활과 성령 강림을 통해 새 시대가 열린다.",
    covenantAxis: "새 언약 · 속죄 · 부활 · 성령",
    themeColor: "#6e2119",
  },
  {
    id: "E15",
    order: 15,
    name: "교회 확장과 사도시대",
    rangeLabel: "사도행전 3-28 · 서신서",
    summary: "예루살렘에서 열방으로 복음이 확장되며 교회와 서신의 시대가 형성된다.",
    covenantAxis: "증언 · 열방 선교 · 교회",
    themeColor: "#285c75",
  },
  {
    id: "E16",
    order: 16,
    name: "재림, 부활, 심판, 새 창조",
    rangeLabel: "고전 15 · 살전 4-5 · 벧후 3 · 계 19-22",
    summary: "신약의 종말 본문이 교회의 소망을 재림과 부활, 심판, 새 창조로 종결시킨다.",
    covenantAxis: "재림 · 부활 · 심판 · 새 창조",
    themeColor: "#325d46",
  },
];

export const controversies = [
  {
    id: "C01",
    title: "출애굽 연대",
    defaultPosition: "메인 타임라인은 상대순서를 우선하고 절대연대는 15세기설과 13세기설을 병기하지 않는다.",
    alternatives: ["B.C. 15세기 중반설", "B.C. 13세기설"],
    whyItMatters: "유월절과 가나안 정복 절대연대는 논쟁적이지만, 구속사적 순서 자체는 흔들지 않는다.",
  },
  {
    id: "C02",
    title: "사사 시대 길이와 중첩",
    defaultPosition: "사사기는 일부 지역 병행성을 인정하되, 타임라인 본체에서는 반복 구조보다 전환 사건에 집중한다.",
    alternatives: ["사사기 연대표를 직렬로 읽는 방식", "지역 중첩을 넓게 보는 방식"],
    whyItMatters: "왕정 전환 전의 시간 길이를 과장하면 본체 타임라인이 불필요하게 불안정해진다.",
  },
  {
    id: "C03",
    title: "욥기 배치",
    defaultPosition: "메인 타임라인에서는 고정 위치를 주지 않고 책-시대 교차표와 논쟁 레지스터에만 둔다.",
    alternatives: ["족장 시대 배치", "지혜문학 편집기 배치"],
    whyItMatters: "본문 배경과 최종 편집 시점을 동일시하지 않기 위해서다.",
  },
  {
    id: "C04",
    title: "복음서 수난주간 조화",
    defaultPosition: "공통으로 겹치는 앵커만 본체에 두고, 세부 일자 조화는 부록 메모로 분리한다.",
    alternatives: ["공관복음 중심 조화", "요한복음 시간표 중심 조화"],
    whyItMatters: "앵커 사건은 동일하지만 세부 시간표는 복음서 간 편집 관점이 개입된다.",
  },
  {
    id: "C05",
    title: "요한계시록과 천년기 세부 순서",
    defaultPosition: "재림, 부활, 심판, 새 창조라는 대축만 본체에 놓고 세부 체계는 메모로 분리한다.",
    alternatives: ["전천년 해석", "무천년 해석", "후천년 해석"],
    whyItMatters: "종말 본체를 유지하면서도 교단별 도식을 강요하지 않기 위함이다.",
  },
];

export const bookPlacements = [
  {
    book: "창세기",
    testament: "OT",
    eraIds: ["E01", "E02", "E03"],
    placementType: "narrative",
    note: "원역사와 족장사를 모두 포함하므로 시대 전환의 기준점으로 사용한다.",
  },
  {
    book: "출애굽기-신명기",
    testament: "OT",
    eraIds: ["E04", "E05"],
    placementType: "narrative",
    note: "출애굽, 시내, 성막, 광야, 모압 갱신을 한 축으로 연결한다.",
  },
  {
    book: "여호수아",
    testament: "OT",
    eraIds: ["E06"],
    placementType: "narrative",
    note: "요단 도하, 정복, 땅 분배와 세겜 갱신을 묶는 중심 서사다.",
  },
  {
    book: "사사기·룻기",
    testament: "OT",
    eraIds: ["E07"],
    placementType: "narrative",
    note: "사사기의 반복 구조와 룻기의 다윗 계보 연결을 함께 본다.",
  },
  {
    book: "사무엘상-열왕기상 11",
    testament: "OT",
    eraIds: ["E07", "E08"],
    placementType: "narrative",
    note: "왕정 전환부터 통일왕국의 정점까지를 서사적으로 잇는다.",
  },
  {
    book: "열왕기상 12-열왕기하",
    testament: "OT",
    eraIds: ["E09", "E10"],
    placementType: "narrative",
    note: "분열왕국, 북왕국 멸망, 유다 말기, 바벨론 포로를 시간축으로 제공한다.",
  },
  {
    book: "역대상·역대하",
    testament: "OT",
    eraIds: ["E08", "E09", "E10"],
    placementType: "narrative",
    note: "다윗 언약과 성전, 유다 중심 관점을 보강하는 병행 서사다.",
  },
  {
    book: "시편",
    testament: "OT",
    eraIds: ["E03", "E07", "E08", "E09", "E10"],
    placementType: "wisdom",
    note: "표제가 있는 시는 해당 역사 지점에 직접 연결하고, 나머지는 시대권으로만 묶는다.",
  },
  {
    book: "잠언·전도서·아가",
    testament: "OT",
    eraIds: ["E08"],
    placementType: "wisdom",
    note: "솔로몬 왕정기를 기본 배치로 삼되 편집 층위는 본체 바깥에 둔다.",
  },
  {
    book: "욥기",
    testament: "OT",
    eraIds: ["E03"],
    placementType: "wisdom",
    note: "족장 시대 배치 가능성을 메모하되 본체 고정은 유보한다.",
  },
  {
    book: "이사야",
    testament: "OT",
    eraIds: ["E09", "E10"],
    placementType: "prophetic",
    note: "웃시야에서 히스기야 시기의 심판과 남은 자 소망을 함께 다룬다.",
  },
  {
    book: "예레미야·예레미야애가",
    testament: "OT",
    eraIds: ["E10"],
    placementType: "prophetic",
    note: "예루살렘 함락과 새 언약 약속의 긴장을 한 시대에 묶는다.",
  },
  {
    book: "에스겔·다니엘",
    testament: "OT",
    eraIds: ["E10"],
    placementType: "prophetic",
    note: "포로지에서의 환상, 회복 약속, 열방 제국 배경을 제공한다.",
  },
  {
    book: "호세아-말라기",
    testament: "OT",
    eraIds: ["E09", "E10", "E11"],
    placementType: "prophetic",
    note: "북왕국과 유다 말기, 귀환 공동체까지 선지자들을 역사 축에 재배치한다.",
  },
  {
    book: "에스라·느헤미야·에스더",
    testament: "OT",
    eraIds: ["E11"],
    placementType: "narrative",
    note: "귀환 공동체의 재건, 개혁, 디아스포라 보존을 한 묶음으로 읽는다.",
  },
  {
    book: "공관복음",
    testament: "NT",
    eraIds: ["E13", "E14"],
    placementType: "narrative",
    note: "메시아 도래, 하나님 나라 선포, 수난주간의 공통 앵커를 제공한다.",
  },
  {
    book: "요한복음",
    testament: "NT",
    eraIds: ["E13", "E14"],
    placementType: "narrative",
    note: "성육신과 영광, 십자가와 부활 해석을 심화하는 해석 복음서로 읽는다.",
  },
  {
    book: "사도행전",
    testament: "NT",
    eraIds: ["E14", "E15"],
    placementType: "narrative",
    note: "승천, 오순절, 예루살렘-사마리아-땅끝 구조를 역사 축으로 제공한다.",
  },
  {
    book: "바울서신",
    testament: "NT",
    eraIds: ["E15"],
    placementType: "epistolary",
    note: "사도행전 이동선 위에 재배치해 선교 시기와 교회 형성 과정을 읽는다.",
  },
  {
    book: "공동서신",
    testament: "NT",
    eraIds: ["E15"],
    placementType: "epistolary",
    note: "흩어진 교회와 박해, 거룩, 소망의 문제를 사도시대 후반 맥락에 둔다.",
  },
  {
    book: "요한계시록",
    testament: "NT",
    eraIds: ["E15", "E16"],
    placementType: "apocalyptic",
    note: "저작 시점은 사도시대 말, 내용상 종말과 새 창조는 최종 시대에 연결한다.",
  },
];

export const rawAnchorEvents = [
  {
    id: "MT-001",
    eraId: "E01",
    titleKo: "창조",
    titleEn: "Creation",
    dateLabel: "원역사",
    rangeLabel: "창세기 1:1-2:3",
    summary: "하나님이 말씀으로 하늘과 땅을 창조하시고 인간을 자기 형상으로 세우신다.",
    significance: "모든 후속 사건은 창조 질서와 하나님의 형상이라는 출발점 위에서만 이해된다.",
    certainty: "A",
    mainPassages: ["창세기 1:1-2:3"],
    keyPassages: ["창세기 1:26-28"],
    fulfillmentPassages: ["요한복음 1:1-3", "골로새서 1:16-17"],
    focusRefs: [nk("창세기", 1, 1, 1, 5), hb("Genesis", 1, 1, 1, 5)],
    originalTerms: [he("בָּרָא", "bara", "창조하다", "창세기 1:1")],
    controversyIds: [],
  },
  {
    id: "MT-002",
    eraId: "E01",
    titleKo: "타락과 원복음",
    titleEn: "Fall and Protoevangelium",
    dateLabel: "원역사",
    rangeLabel: "창세기 3:1-24",
    summary: "인간의 반역으로 죄와 저주가 세상에 들어오지만 여자의 후손 약속이 함께 선포된다.",
    significance: "심판 속에 약속이 함께 놓이는 구조가 이후의 모든 구속사 전개를 이끈다.",
    certainty: "A",
    mainPassages: ["창세기 3:1-24"],
    keyPassages: ["창세기 3:15"],
    fulfillmentPassages: ["로마서 16:20", "갈라디아서 4:4-5"],
    focusRefs: [nk("창세기", 3, 14, 3, 19), hb("Genesis", 3, 14, 3, 19)],
    originalTerms: [he("זֶרַע", "zera", "씨, 후손", "창세기 3:15")],
    controversyIds: [],
  },
  {
    id: "MT-003",
    eraId: "E02",
    titleKo: "홍수 심판과 노아 언약",
    titleEn: "Flood and Noahic Covenant",
    dateLabel: "원역사",
    rangeLabel: "창세기 6:5-9:17",
    summary: "하나님은 홍수로 세상을 심판하시되 노아를 통해 피조세계를 보존하는 언약을 세우신다.",
    significance: "보존 언약은 구속사 진행의 역사 무대를 유지하는 공적 약속이 된다.",
    certainty: "A",
    mainPassages: ["창세기 6:5-9:17"],
    keyPassages: ["창세기 8:20-22", "창세기 9:8-17"],
    fulfillmentPassages: ["베드로전서 3:20-21"],
    focusRefs: [nk("창세기", 9, 8, 9, 17), hb("Genesis", 9, 8, 9, 17)],
    originalTerms: [he("בְּרִית", "berit", "언약", "창세기 9:9")],
    controversyIds: [],
  },
  {
    id: "MT-004",
    eraId: "E02",
    titleKo: "바벨과 열국 분산",
    titleEn: "Babel and the Nations",
    dateLabel: "원역사",
    rangeLabel: "창세기 11:1-9",
    summary: "인류의 자기 이름 세우기 시도가 무너지고 언어 혼잡과 열국 분산이 뒤따른다.",
    significance: "열방 문제는 심판의 결과이면서 동시에 이후 아브라함 약속의 배경이 된다.",
    certainty: "A",
    mainPassages: ["창세기 11:1-9"],
    keyPassages: ["창세기 11:4-9"],
    fulfillmentPassages: ["사도행전 2:5-11"],
    focusRefs: [nk("창세기", 11, 1, 11, 9), hb("Genesis", 11, 1, 11, 9)],
    originalTerms: [he("בָּלַל", "balal", "혼잡하게 하다", "창세기 11:9")],
    controversyIds: [],
  },
  {
    id: "MT-005",
    eraId: "E03",
    titleKo: "아브라함 소명",
    titleEn: "Call of Abram",
    dateLabel: "B.C. 2000경",
    rangeLabel: "창세기 12:1-9",
    summary: "하나님은 아브람을 불러 땅과 씨와 복의 약속을 주시며 한 사람에게 역사를 집중하신다.",
    significance: "열방을 향한 복의 경로가 아브라함 계보 안으로 수렴되며 성경 전체의 중축이 형성된다.",
    certainty: "A",
    mainPassages: ["창세기 12:1-9"],
    keyPassages: ["창세기 12:1-3"],
    fulfillmentPassages: ["갈라디아서 3:8-9", "히브리서 11:8-10"],
    focusRefs: [nk("창세기", 12, 1, 12, 4), hb("Genesis", 12, 1, 12, 4)],
    originalTerms: [he("בָּרַךְ", "barakh", "복 주다", "창세기 12:2-3")],
    controversyIds: [],
  },
  {
    id: "MT-006",
    eraId: "E03",
    titleKo: "아브라함 언약 체결",
    titleEn: "Abrahamic Covenant",
    dateLabel: "B.C. 2000경",
    rangeLabel: "창세기 15:1-21 · 17:1-14",
    summary: "하나님이 아브라함과 언약을 세우시고 약속의 씨와 땅을 표지와 함께 확정하신다.",
    significance: "약속은 추상적 위로가 아니라 언약적 확약으로 고정되며 이후의 구속사 구조를 지배한다.",
    certainty: "A",
    mainPassages: ["창세기 15:1-21", "창세기 17:1-14"],
    keyPassages: ["창세기 15:5-6", "창세기 17:7"],
    fulfillmentPassages: ["로마서 4:3", "누가복음 1:72-73"],
    focusRefs: [nk("창세기", 15, 5, 15, 6), hb("Genesis", 15, 5, 15, 6)],
    originalTerms: [he("בְּרִית", "berit", "언약", "창세기 15:18", "창세기 17:7")],
    controversyIds: [],
  },
  {
    id: "MT-007",
    eraId: "E03",
    titleKo: "야곱/이스라엘 형성과 언약 계승",
    titleEn: "Jacob and Israel",
    dateLabel: "족장 시대",
    rangeLabel: "창세기 28:10-22 · 35:9-15",
    summary: "야곱이 이스라엘로 이름을 받고 조상들에게 주어진 약속이 열두 지파의 틀로 계승된다.",
    significance: "약속의 씨가 민족적 형상을 띠며 하나님 백성의 이름과 정체성이 형성된다.",
    certainty: "A",
    mainPassages: ["창세기 28:10-22", "창세기 35:9-15"],
    keyPassages: ["창세기 28:13-15", "창세기 35:10-12"],
    fulfillmentPassages: ["요한복음 1:51"],
    focusRefs: [nk("창세기", 28, 13, 28, 15), hb("Genesis", 28, 13, 28, 15)],
    originalTerms: [he("יִשְׂרָאֵל", "yisra'el", "이스라엘", "창세기 35:10")],
    controversyIds: [],
  },
  {
    id: "MT-008",
    eraId: "E03",
    titleKo: "요셉을 통한 보존과 애굽 이주",
    titleEn: "Joseph and Preservation",
    dateLabel: "족장 말기",
    rangeLabel: "창세기 37-50",
    summary: "요셉의 고난과 승격을 통해 약속 계보가 기근 속에서도 보존되고 애굽 정착이 준비된다.",
    significance: "인간의 악의가 하나님의 보존 섭리로 전환되며 출애굽의 배경이 마련된다.",
    certainty: "A",
    mainPassages: ["창세기 45:4-8", "창세기 46:1-7", "창세기 50:19-21"],
    keyPassages: ["창세기 45:5-8", "창세기 50:20"],
    fulfillmentPassages: ["사도행전 7:9-14"],
    focusRefs: [nk("창세기", 45, 5, 45, 8), hb("Genesis", 45, 5, 45, 8)],
    originalTerms: [he("שָׁלַח", "shalach", "보내다", "창세기 45:5", "창세기 45:7")],
    controversyIds: [],
  },
  {
    id: "MT-009",
    eraId: "E04",
    titleKo: "모세 소명",
    titleEn: "Call of Moses",
    dateLabel: "출애굽 직전",
    rangeLabel: "출애굽기 3:1-4:17",
    summary: "하나님은 떨기나무 가운데서 모세를 부르시고 자기 이름으로 구속 사명을 위임하신다.",
    significance: "출애굽 사건은 단순 민족 이동이 아니라 하나님의 자기 계시와 연결된 구속 행위다.",
    certainty: "A",
    mainPassages: ["출애굽기 3:1-4:17"],
    keyPassages: ["출애굽기 3:6-10", "출애굽기 3:14"],
    fulfillmentPassages: ["사도행전 7:30-34"],
    focusRefs: [nk("출애굽기", 3, 7, 3, 10), hb("Exodus", 3, 7, 3, 10)],
    originalTerms: [he("אֶהְיֶה", "ehyeh", "나는 스스로 있는 자", "출애굽기 3:14")],
    controversyIds: [],
  },
  {
    id: "MT-010",
    eraId: "E04",
    titleKo: "유월절과 출애굽",
    titleEn: "Passover and Exodus",
    dateLabel: "B.C. 15세기/13세기 논쟁",
    rangeLabel: "출애굽기 12:1-14:31",
    summary: "유월절 희생과 홍해 구원을 통해 하나님이 자기 백성을 집단적으로 건져내신다.",
    significance: "구약의 대표 구속 사건이 세워지며 이후 속죄와 구원의 어휘를 결정한다.",
    certainty: "A",
    mainPassages: ["출애굽기 12:1-14", "출애굽기 14:13-31"],
    keyPassages: ["출애굽기 12:13-14"],
    fulfillmentPassages: ["고린도전서 5:7", "누가복음 22:15-20"],
    focusRefs: [nk("출애굽기", 12, 13, 12, 14), hb("Exodus", 12, 13, 12, 14)],
    originalTerms: [he("פֶּסַח", "pesach", "유월절", "출애굽기 12:11", "출애굽기 12:27")],
    controversyIds: ["C01"],
  },
  {
    id: "MT-011",
    eraId: "E04",
    titleKo: "시내 언약 체결",
    titleEn: "Sinai Covenant",
    dateLabel: "출애굽 직후",
    rangeLabel: "출애굽기 19:1-24:18",
    summary: "하나님은 구속받은 백성을 제사장 나라와 거룩한 백성으로 부르며 언약을 체결하신다.",
    significance: "언약 백성의 정체성, 율법, 예배, 공동체 질서가 한 번에 공적으로 제정된다.",
    certainty: "A",
    mainPassages: ["출애굽기 19:1-8", "출애굽기 24:3-8"],
    keyPassages: ["출애굽기 19:4-6", "출애굽기 24:8"],
    fulfillmentPassages: ["베드로전서 2:9", "히브리서 9:18-20"],
    focusRefs: [nk("출애굽기", 19, 4, 19, 6), hb("Exodus", 19, 4, 19, 6)],
    originalTerms: [he("סְגֻלָּה", "segullah", "자기 소유", "출애굽기 19:5")],
    controversyIds: [],
  },
  {
    id: "MT-012",
    eraId: "E05",
    titleKo: "성막 건립과 여호와의 영광 임재",
    titleEn: "Tabernacle and Glory",
    dateLabel: "광야 초기",
    rangeLabel: "출애굽기 25-40",
    summary: "성막이 세워지고 여호와의 영광이 그 가운데 임해 하나님 백성 가운데 거하심을 드러낸다.",
    significance: "임재의 문제는 광야 공동체의 중심이며 이후 성전 신학과 성육신 이해의 선행 그림이 된다.",
    certainty: "A",
    mainPassages: ["출애굽기 25:8-9", "출애굽기 40:34-38"],
    keyPassages: ["출애굽기 29:45-46"],
    fulfillmentPassages: ["요한복음 1:14", "요한계시록 21:3"],
    focusRefs: [nk("출애굽기", 40, 34, 40, 38), hb("Exodus", 40, 34, 40, 38)],
    originalTerms: [he("שָׁכַן", "shakan", "거하다", "출애굽기 25:8", "출애굽기 29:45")],
    controversyIds: [],
  },
  {
    id: "MT-013",
    eraId: "E05",
    titleKo: "광야 심판과 모압 언약 갱신",
    titleEn: "Wilderness Judgment and Moab Renewal",
    dateLabel: "광야 후반",
    rangeLabel: "민수기 13-14 · 신명기 29-30",
    summary: "불신앙으로 한 세대가 광야에서 쓰러지고, 모압 평지에서 새 세대를 향한 언약 갱신이 선포된다.",
    significance: "출애굽 세대의 실패는 다음 세대를 향한 순종 요구와 마음의 할례 약속으로 이어진다.",
    certainty: "B",
    mainPassages: ["민수기 14:20-23", "신명기 30:1-10"],
    keyPassages: ["민수기 14:22-23", "신명기 30:6"],
    fulfillmentPassages: ["로마서 2:29", "골로새서 2:11"],
    focusRefs: [nk("신명기", 30, 1, 30, 6), hb("Deuteronomy", 30, 1, 30, 6)],
    originalTerms: [he("שׁוּב", "shuv", "돌이키다", "신명기 30:2", "신명기 30:3")],
    controversyIds: ["C01"],
  },
  {
    id: "MT-014",
    eraId: "E06",
    titleKo: "요단 도하와 정복 개시",
    titleEn: "Jordan Crossing and Conquest",
    dateLabel: "가나안 진입",
    rangeLabel: "여호수아 3-6",
    summary: "언약궤가 요단을 앞서고, 여리고 함락으로 가나안 정복의 첫 표지가 세워진다.",
    significance: "출애굽의 물 건넘이 땅 진입에서 반복되며 약속의 땅이 실제 기업으로 전환된다.",
    certainty: "A",
    mainPassages: ["여호수아 3:14-17", "여호수아 6:20"],
    keyPassages: ["여호수아 3:5", "여호수아 3:17"],
    fulfillmentPassages: ["히브리서 11:29-30"],
    focusRefs: [nk("여호수아", 3, 14, 3, 17), hb("Joshua", 3, 14, 3, 17)],
    originalTerms: [he("עָבַר", "avar", "건너다", "여호수아 3:16", "여호수아 4:22")],
    controversyIds: [],
  },
  {
    id: "MT-015",
    eraId: "E06",
    titleKo: "땅 분배와 세겜 언약 갱신",
    titleEn: "Land Allotment and Shechem Renewal",
    dateLabel: "정복 후반",
    rangeLabel: "여호수아 13-24",
    summary: "기업 분배가 마무리되고 세겜에서 언약 갱신이 이루어져 땅과 순종이 다시 연결된다.",
    significance: "땅은 단순 영토가 아니라 언약 순종과 결합된 기업으로 제시된다.",
    certainty: "A",
    mainPassages: ["여호수아 13:1-7", "여호수아 24:14-25"],
    keyPassages: ["여호수아 21:43-45", "여호수아 24:14-15"],
    fulfillmentPassages: ["히브리서 4:8-9"],
    focusRefs: [nk("여호수아", 24, 14, 24, 25), hb("Joshua", 24, 14, 24, 25)],
    originalTerms: [he("נַחֲלָה", "nahalah", "기업", "여호수아 13:6", "여호수아 24:32")],
    controversyIds: [],
  },
  {
    id: "MT-016",
    eraId: "E07",
    titleKo: "사무엘 사역과 왕정 전환",
    titleEn: "Samuel and the Monarchy Shift",
    dateLabel: "B.C. 11세기",
    rangeLabel: "사무엘상 7-10",
    summary: "사무엘이 사사 시대를 마감하고 왕정 제도의 문을 열며 이스라엘의 정치 구조가 전환된다.",
    significance: "왕정은 인간의 욕망을 드러내는 동시에 다윗 언약으로 이어질 통치 구조를 예비한다.",
    certainty: "A",
    mainPassages: ["사무엘상 7:3-13", "사무엘상 8:4-22", "사무엘상 10:17-25"],
    keyPassages: ["사무엘상 8:7", "사무엘상 10:24-25"],
    fulfillmentPassages: ["사도행전 13:20-22"],
    focusRefs: [nk("사무엘상", 8, 6, 8, 9), hb("1 Samuel", 8, 6, 8, 9)],
    originalTerms: [he("מֶלֶךְ", "melek", "왕", "사무엘상 8:5", "사무엘상 8:7")],
    controversyIds: ["C02"],
  },
  {
    id: "MT-017",
    eraId: "E08",
    titleKo: "다윗 왕권 확립과 예루살렘 점령",
    titleEn: "Davidic Kingship Established",
    dateLabel: "B.C. 1000경",
    rangeLabel: "사무엘하 5:1-10",
    summary: "다윗이 온 이스라엘의 왕이 되고 예루살렘을 점령해 통치 중심지를 확립한다.",
    significance: "예루살렘과 다윗 왕권의 결합은 이후 메시아 기대의 지리적·정치적 중심이 된다.",
    certainty: "A",
    mainPassages: ["사무엘하 5:1-10"],
    keyPassages: ["사무엘하 5:2", "사무엘하 5:7"],
    fulfillmentPassages: ["누가복음 1:32-33"],
    focusRefs: [nk("사무엘하", 5, 1, 5, 5), hb("2 Samuel", 5, 1, 5, 5)],
    originalTerms: [he("מֶלֶךְ", "melek", "왕", "사무엘하 5:3")],
    controversyIds: [],
  },
  {
    id: "MT-018",
    eraId: "E08",
    titleKo: "다윗 언약",
    titleEn: "Davidic Covenant",
    dateLabel: "B.C. 1000경",
    rangeLabel: "사무엘하 7:8-16",
    summary: "하나님이 다윗에게 집과 왕위가 영원히 견고하리라는 언약을 주신다.",
    significance: "메시아 왕권은 다윗 언약 안에서 왕적·언약적 형태를 얻게 된다.",
    certainty: "A",
    mainPassages: ["사무엘하 7:8-16"],
    keyPassages: ["사무엘하 7:12-16"],
    fulfillmentPassages: ["누가복음 1:32-33", "사도행전 2:30-36"],
    focusRefs: [nk("사무엘하", 7, 12, 7, 16), hb("2 Samuel", 7, 12, 7, 16)],
    originalTerms: [he("בַּיִת", "bayit", "집, 왕조", "사무엘하 7:11", "사무엘하 7:16")],
    controversyIds: [],
  },
  {
    id: "MT-019",
    eraId: "E08",
    titleKo: "성전 건축과 봉헌",
    titleEn: "Temple Construction and Dedication",
    dateLabel: "통일왕국",
    rangeLabel: "열왕기상 6-8",
    summary: "솔로몬이 성전을 건축하고 봉헌하며 여호와의 이름을 위한 집이 예루살렘에 세워진다.",
    significance: "성전은 하나님 임재와 왕국 질서의 가시적 중심이지만, 동시에 더 큰 성전의 예표가 된다.",
    certainty: "A",
    mainPassages: ["열왕기상 8:22-30", "열왕기상 8:54-61"],
    keyPassages: ["열왕기상 8:27-30"],
    fulfillmentPassages: ["요한복음 2:19-21", "에베소서 2:20-22"],
    focusRefs: [nk("열왕기상", 8, 27, 8, 30), hb("1 Kings", 8, 27, 8, 30)],
    originalTerms: [he("כָּבוֹד", "kavod", "영광", "열왕기상 8:11")],
    controversyIds: [],
  },
  {
    id: "MT-020",
    eraId: "E09",
    titleKo: "왕국 분열",
    titleEn: "Division of the Kingdom",
    dateLabel: "B.C. 930경",
    rangeLabel: "열왕기상 12:1-24",
    summary: "르호보암의 완고함과 하나님의 심판 아래 나라가 북과 남으로 갈라진다.",
    significance: "분열은 단순 정치 분쟁이 아니라 언약 불순종에 대한 역사적 파열로 제시된다.",
    certainty: "A",
    mainPassages: ["열왕기상 12:1-24"],
    keyPassages: ["열왕기상 12:15-16"],
    fulfillmentPassages: [],
    focusRefs: [nk("열왕기상", 12, 15, 12, 20), hb("1 Kings", 12, 15, 12, 20)],
    originalTerms: [he("קָרַע", "qara", "찢다", "열왕기상 11:31", "열왕기상 12:15")],
    controversyIds: [],
  },
  {
    id: "MT-021",
    eraId: "E09",
    titleKo: "엘리야의 갈멜산 대결과 언약 소송",
    titleEn: "Elijah at Carmel",
    dateLabel: "북왕국",
    rangeLabel: "열왕기상 18:20-39",
    summary: "갈멜산에서 여호와와 바알 중 누가 참 하나님인지 공개적으로 판결된다.",
    significance: "선지자 사역은 역사 해설이 아니라 언약 소송과 회개의 소환이라는 성격을 드러낸다.",
    certainty: "A",
    mainPassages: ["열왕기상 18:20-39"],
    keyPassages: ["열왕기상 18:36-39"],
    fulfillmentPassages: ["야고보서 5:17-18"],
    focusRefs: [nk("열왕기상", 18, 36, 18, 39), hb("1 Kings", 18, 36, 18, 39)],
    originalTerms: [he("קָנָא", "qana", "질투하다, 열심내다", "열왕기상 19:10")],
    controversyIds: [],
  },
  {
    id: "MT-022",
    eraId: "E09",
    titleKo: "북왕국 멸망",
    titleEn: "Fall of the Northern Kingdom",
    dateLabel: "B.C. 722경",
    rangeLabel: "열왕기하 17:1-23",
    summary: "앗수르가 사마리아를 함락시키고 북왕국은 언약 불순종의 결과로 역사 무대에서 사라진다.",
    significance: "선지자 경고는 실제 역사 심판으로 이어지며 언약 위반의 무게를 드러낸다.",
    certainty: "A",
    mainPassages: ["열왕기하 17:1-23"],
    keyPassages: ["열왕기하 17:7-18"],
    fulfillmentPassages: [],
    focusRefs: [nk("열왕기하", 17, 7, 17, 18), hb("2 Kings", 17, 7, 17, 18)],
    originalTerms: [he("גָּלָה", "galah", "사로잡혀 가다", "열왕기하 17:6", "열왕기하 17:23")],
    controversyIds: [],
  },
  {
    id: "MT-023",
    eraId: "E10",
    titleKo: "히스기야 개혁과 앗수르 위기에서의 구원",
    titleEn: "Hezekiah and Deliverance",
    dateLabel: "B.C. 701경",
    rangeLabel: "열왕기하 18-19 · 이사야 36-37",
    summary: "히스기야 시대에 유다가 개혁을 경험하고 앗수르의 위기 속에서 하나님의 구원을 본다.",
    significance: "남은 자 소망과 왕권 보호는 포로 직전 시대에도 여전히 유효한 약속임을 보여 준다.",
    certainty: "B",
    mainPassages: ["열왕기하 18:1-6", "열왕기하 19:32-35"],
    keyPassages: ["열왕기하 19:34"],
    fulfillmentPassages: [],
    focusRefs: [nk("열왕기하", 19, 32, 19, 35), hb("2 Kings", 19, 32, 19, 35)],
    originalTerms: [he("יְשׁוּעָה", "yeshuah", "구원", "열왕기하 19:34")],
    controversyIds: [],
  },
  {
    id: "MT-024",
    eraId: "E10",
    titleKo: "요시야 개혁과 율법책 회복",
    titleEn: "Josiah's Reform",
    dateLabel: "B.C. 7세기 후반",
    rangeLabel: "열왕기하 22-23",
    summary: "성전에서 율법책이 발견되고 요시야가 공개적 언약 갱신과 종교 개혁을 단행한다.",
    significance: "말기 유다의 마지막 개혁은 율법 중심 언약 갱신이 얼마나 급진적으로 요구되었는지 보여 준다.",
    certainty: "A",
    mainPassages: ["열왕기하 22:8-13", "열왕기하 23:1-3"],
    keyPassages: ["열왕기하 23:3"],
    fulfillmentPassages: [],
    focusRefs: [nk("열왕기하", 23, 1, 23, 3), hb("2 Kings", 23, 1, 23, 3)],
    originalTerms: [he("תּוֹרָה", "torah", "율법", "열왕기하 22:8", "열왕기하 23:24")],
    controversyIds: [],
  },
  {
    id: "MT-025",
    eraId: "E10",
    titleKo: "예루살렘 함락과 바벨론 포로",
    titleEn: "Fall of Jerusalem and Exile",
    dateLabel: "B.C. 586경",
    rangeLabel: "열왕기하 24-25 · 역대하 36:11-21",
    summary: "예루살렘과 성전이 무너지고 유다 백성은 바벨론으로 끌려가며 언약 심판이 완결된다.",
    significance: "포로는 왕국과 성전 체제가 무너지는 총체적 단절이지만, 동시에 회복 약속을 위한 어두운 배경이 된다.",
    certainty: "A",
    mainPassages: ["열왕기하 25:8-12", "역대하 36:17-21"],
    keyPassages: ["열왕기하 25:9", "역대하 36:21"],
    fulfillmentPassages: [],
    focusRefs: [nk("열왕기하", 25, 8, 25, 12), hb("2 Kings", 25, 8, 25, 12)],
    originalTerms: [he("חָרַב", "charav", "폐허가 되다", "열왕기하 25:9")],
    controversyIds: [],
  },
  {
    id: "MT-026",
    eraId: "E10",
    titleKo: "새 언약과 회복 약속",
    titleEn: "New Covenant Promise",
    dateLabel: "포로기 예언",
    rangeLabel: "예레미야 31:31-34 · 에스겔 36:22-28",
    summary: "하나님은 포로의 한가운데서 새 마음과 새 영, 새 언약의 회복을 약속하신다.",
    significance: "회복은 단순 귀환이 아니라 마음을 바꾸는 새 언약 행위로 제시된다.",
    certainty: "A",
    mainPassages: ["예레미야 31:31-34", "에스겔 36:22-28"],
    keyPassages: ["예레미야 31:33", "에스겔 36:26-27"],
    fulfillmentPassages: ["누가복음 22:20", "히브리서 8:8-12"],
    focusRefs: [nk("예레미야", 31, 31, 31, 34), hb("Jeremiah", 31, 31, 31, 34)],
    originalTerms: [he("חָדָשׁ", "chadash", "새로운", "예레미야 31:31", "에스겔 36:26")],
    controversyIds: [],
  },
  {
    id: "MT-027",
    eraId: "E11",
    titleKo: "고레스 칙령과 1차 귀환",
    titleEn: "Cyrus Decree and Return",
    dateLabel: "B.C. 538경",
    rangeLabel: "에스라 1-2",
    summary: "고레스의 칙령 아래 성전 재건을 위한 1차 귀환이 시작된다.",
    significance: "포로의 끝은 열방 왕의 칙령을 통해 오지만, 실제 주도권은 언약의 하나님께 있음을 드러낸다.",
    certainty: "A",
    mainPassages: ["에스라 1:1-5", "에스라 2:64-70"],
    keyPassages: ["에스라 1:1-3"],
    fulfillmentPassages: [],
    focusRefs: [nk("에스라", 1, 1, 1, 5), hb("Ezra", 1, 1, 1, 5)],
    originalTerms: [he("שׁוּב", "shuv", "돌아오다", "에스라 1:3", "에스라 2:1")],
    controversyIds: [],
  },
  {
    id: "MT-028",
    eraId: "E11",
    titleKo: "성전 재건 완성",
    titleEn: "Temple Rebuilt",
    dateLabel: "B.C. 516경",
    rangeLabel: "에스라 3-6 · 학개 1-2 · 스가랴 1-8",
    summary: "중단되었던 성전 공사가 선지자들의 권면 속에 다시 시작되어 완공된다.",
    significance: "귀환 공동체의 중심은 정치적 독립이 아니라 예배 회복과 임재의 재정렬에 있다.",
    certainty: "A",
    mainPassages: ["에스라 6:14-18"],
    keyPassages: ["학개 2:4-9"],
    fulfillmentPassages: [],
    focusRefs: [nk("에스라", 6, 14, 6, 18), hb("Ezra", 6, 14, 6, 18)],
    originalTerms: [he("בַּיִת", "bayit", "집, 성전", "학개 1:4", "에스라 6:15")],
    controversyIds: [],
  },
  {
    id: "MT-029",
    eraId: "E11",
    titleKo: "에스라-느헤미야 개혁과 언약 갱신",
    titleEn: "Ezra-Nehemiah Reform",
    dateLabel: "귀환 공동체",
    rangeLabel: "에스라 7-10 · 느헤미야 1-10",
    summary: "말씀 낭독과 회개, 성벽 재건과 언약 서약을 통해 공동체 정체성이 다시 세워진다.",
    significance: "포로 이후의 회복은 성전만이 아니라 말씀 중심 공동체의 재구성까지 포함한다.",
    certainty: "A",
    mainPassages: ["느헤미야 8:1-8", "느헤미야 9:38-10:29"],
    keyPassages: ["느헤미야 8:8", "느헤미야 10:29"],
    fulfillmentPassages: [],
    focusRefs: [nk("느헤미야", 8, 1, 8, 8), hb("Nehemiah", 8, 1, 8, 8)],
    originalTerms: [he("קָהָל", "qahal", "회중, 집회", "느헤미야 8:2", "느헤미야 8:17")],
    controversyIds: [],
  },
  {
    id: "MT-030",
    eraId: "E13",
    titleKo: "성육신과 메시아 탄생",
    titleEn: "Incarnation and Birth of the Messiah",
    dateLabel: "A.D. 1세기 초",
    rangeLabel: "마태복음 1-2 · 누가복음 1-2 · 요한복음 1:14",
    summary: "예수의 탄생과 성육신이 구약의 약속을 역사 한복판에 도래하게 한다.",
    significance: "메시아의 도래는 구속사 전체가 한 인격 안에 집중되는 전환점이다.",
    certainty: "A",
    mainPassages: ["누가복음 2:10-14", "요한복음 1:14"],
    keyPassages: ["마태복음 1:21-23"],
    fulfillmentPassages: ["이사야 7:14", "미가 5:2"],
    focusRefs: [nk("누가복음", 2, 10, 2, 14), gr("누가복음", "LUK", 2, 10, 2, 14)],
    originalTerms: [ge("σὰρξ", "sarx", "육신", "요한복음 1:14")],
    controversyIds: [],
  },
  {
    id: "MT-031",
    eraId: "E13",
    titleKo: "세례, 하나님 나라 선포, 제자 공동체 형성",
    titleEn: "Baptism, Kingdom Proclamation, and Disciples",
    dateLabel: "공생애 시작",
    rangeLabel: "마태복음 3-7 · 마가복음 1-3 · 누가복음 3-6",
    summary: "예수는 세례를 받으신 뒤 하나님 나라를 선포하고 제자 공동체를 부르신다.",
    significance: "메시아의 사역은 왕국 선포와 새 백성 형성이라는 두 축으로 진행된다.",
    certainty: "A",
    mainPassages: ["마가복음 1:14-20"],
    keyPassages: ["마태복음 3:16-17", "마가복음 1:15"],
    fulfillmentPassages: ["이사야 61:1-2", "이사야 9:1-2"],
    focusRefs: [nk("마가복음", 1, 14, 1, 18), gr("마가복음", "MRK", 1, 14, 1, 18)],
    originalTerms: [ge("βασιλεία", "basileia", "나라, 왕권", "마가복음 1:15")],
    controversyIds: [],
  },
  {
    id: "MT-032",
    eraId: "E14",
    titleKo: "최후의 만찬과 새 언약 선언",
    titleEn: "Last Supper and New Covenant",
    dateLabel: "수난주간",
    rangeLabel: "누가복음 22:14-20",
    summary: "예수는 유월절 식탁에서 자신의 피를 새 언약의 피로 해석하며 제자들에게 잔을 주신다.",
    significance: "출애굽의 기억은 이제 메시아의 죽음을 중심으로 재정의되며 새 언약이 선언된다.",
    certainty: "A",
    mainPassages: ["누가복음 22:14-20"],
    keyPassages: ["누가복음 22:19-20"],
    fulfillmentPassages: ["예레미야 31:31-34", "출애굽기 24:8"],
    focusRefs: [nk("누가복음", 22, 19, 22, 20), gr("누가복음", "LUK", 22, 19, 22, 20)],
    originalTerms: [ge("διαθήκη", "diatheke", "언약", "누가복음 22:20")],
    controversyIds: ["C04"],
  },
  {
    id: "MT-033",
    eraId: "E14",
    titleKo: "십자가 죽음과 속죄",
    titleEn: "Crucifixion and Atonement",
    dateLabel: "A.D. 30경",
    rangeLabel: "마태복음 27 · 마가복음 15 · 누가복음 23 · 요한복음 19",
    summary: "예수는 십자가에서 죽으심으로 새 언약의 피를 실제로 흘리고 속죄를 성취하신다.",
    significance: "구속사는 십자가에서 정점을 찍고, 모든 제사와 희생의 언어가 여기서 수렴된다.",
    certainty: "A",
    mainPassages: ["요한복음 19:28-30"],
    keyPassages: ["마가복음 15:39", "요한복음 19:30"],
    fulfillmentPassages: ["이사야 53:4-6", "히브리서 9:12"],
    focusRefs: [nk("요한복음", 19, 28, 19, 30), gr("요한복음", "JHN", 19, 28, 19, 30)],
    originalTerms: [ge("τετέλεσται", "tetelestai", "다 이루었다", "요한복음 19:30")],
    controversyIds: ["C04"],
  },
  {
    id: "MT-034",
    eraId: "E14",
    titleKo: "부활",
    titleEn: "Resurrection",
    dateLabel: "A.D. 30경",
    rangeLabel: "마태복음 28 · 누가복음 24 · 요한복음 20-21",
    summary: "예수는 죽음을 깨뜨리고 부활하셔서 새 창조의 첫 열매로 서신다.",
    significance: "부활은 십자가의 승인을 넘어 새 시대의 개시와 종말 소망의 근거가 된다.",
    certainty: "A",
    mainPassages: ["요한복음 20:19-20", "누가복음 24:36-43"],
    keyPassages: ["마태복음 28:5-7"],
    fulfillmentPassages: ["고린도전서 15:20-23"],
    focusRefs: [nk("요한복음", 20, 19, 20, 20), gr("요한복음", "JHN", 20, 19, 20, 20)],
    originalTerms: [ge("ἀνάστασις", "anastasis", "부활", "요한복음 11:25", "고린도전서 15:20")],
    controversyIds: ["C04"],
  },
  {
    id: "MT-035",
    eraId: "E14",
    titleKo: "승천과 오순절",
    titleEn: "Ascension and Pentecost",
    dateLabel: "초대교회 시작",
    rangeLabel: "사도행전 1-2",
    summary: "예수의 승천 뒤 성령이 강림하고, 교회는 공개적 증언 공동체로 출발한다.",
    significance: "메시아의 구원 사역은 성령의 부으심을 통해 교회 시대의 현실로 전환된다.",
    certainty: "A",
    mainPassages: ["사도행전 1:8", "사도행전 2:1-4"],
    keyPassages: ["사도행전 2:33"],
    fulfillmentPassages: ["요엘 2:28-32"],
    focusRefs: [nk("사도행전", 2, 1, 2, 4), gr("사도행전", "ACT", 2, 1, 2, 4)],
    originalTerms: [ge("πνεῦμα", "pneuma", "영, 성령", "사도행전 2:4", "사도행전 2:17")],
    controversyIds: [],
  },
  {
    id: "MT-036",
    eraId: "E15",
    titleKo: "예루살렘 증언과 박해를 통한 확장",
    titleEn: "Jerusalem Witness and Expansion",
    dateLabel: "사도시대 초반",
    rangeLabel: "사도행전 3-8",
    summary: "예루살렘 교회는 능력 있게 증언하지만 박해를 통해 유대와 사마리아로 흩어진다.",
    significance: "박해는 실패가 아니라 복음 확장의 동력으로 재해석된다.",
    certainty: "A",
    mainPassages: ["사도행전 4:31-33", "사도행전 8:4-8"],
    keyPassages: ["사도행전 1:8", "사도행전 8:4"],
    fulfillmentPassages: [],
    focusRefs: [nk("사도행전", 8, 4, 8, 8), gr("사도행전", "ACT", 8, 4, 8, 8)],
    originalTerms: [ge("μαρτυρία", "martyria", "증언", "사도행전 4:33")],
    controversyIds: [],
  },
  {
    id: "MT-037",
    eraId: "E15",
    titleKo: "이방 선교 전환과 바울 선교의 확장",
    titleEn: "Gentile Mission and Pauline Expansion",
    dateLabel: "사도시대 중후반",
    rangeLabel: "사도행전 10-28",
    summary: "복음은 고넬료 사건과 바울 사역을 통해 본격적으로 이방 세계로 확장된다.",
    significance: "아브라함에게 약속된 열방의 복이 사도 선교와 서신 형성 속에서 가시화된다.",
    certainty: "A",
    mainPassages: ["사도행전 10:34-48", "사도행전 13:46-48"],
    keyPassages: ["사도행전 13:47-48", "사도행전 28:28"],
    fulfillmentPassages: ["이사야 49:6"],
    focusRefs: [nk("사도행전", 13, 46, 13, 48), gr("사도행전", "ACT", 13, 46, 13, 48)],
    originalTerms: [ge("ἔθνη", "ethne", "열방, 이방인", "사도행전 13:47")],
    controversyIds: [],
  },
  {
    id: "MT-038",
    eraId: "E16",
    titleKo: "재림과 성도의 부활",
    titleEn: "Return of Christ and Resurrection",
    dateLabel: "종말 소망",
    rangeLabel: "데살로니가전서 4:13-18 · 고린도전서 15:20-58 · 요한계시록 19:11-21",
    summary: "주께서 다시 오실 때 죽은 자가 부활하고 살아 있는 성도도 변화된 몸으로 주를 맞는다.",
    significance: "교회의 소망은 영혼의 지속이 아니라 몸의 부활과 주의 재림에 고정된다.",
    certainty: "B",
    mainPassages: ["데살로니가전서 4:16-17", "고린도전서 15:51-54"],
    keyPassages: ["고린도전서 15:20-23"],
    fulfillmentPassages: [],
    focusRefs: [nk("데살로니가전서", 4, 16, 4, 17), gr("데살로니가전서", "1TH", 4, 16, 4, 17)],
    originalTerms: [ge("παρουσία", "parousia", "임재, 재림", "데살로니가전서 4:15")],
    controversyIds: ["C05"],
  },
  {
    id: "MT-039",
    eraId: "E16",
    titleKo: "최후 심판",
    titleEn: "Final Judgment",
    dateLabel: "종말 소망",
    rangeLabel: "요한계시록 20:11-15",
    summary: "크고 흰 보좌 앞에서 죽은 자들이 행위대로 심판을 받고 생명책이 최종 기준으로 드러난다.",
    significance: "구속사는 결국 하나님의 공의 앞에서 모든 역사를 평가하는 심판으로 닫힌다.",
    certainty: "B",
    mainPassages: ["요한계시록 20:11-15"],
    keyPassages: ["요한계시록 20:12", "요한계시록 20:15"],
    fulfillmentPassages: [],
    focusRefs: [nk("요한계시록", 20, 11, 20, 15), gr("요한계시록", "REV", 20, 11, 20, 15)],
    originalTerms: [ge("κρίσις", "krisis", "심판", "요한계시록 20:12")],
    controversyIds: ["C05"],
  },
  {
    id: "MT-040",
    eraId: "E16",
    titleKo: "새 하늘과 새 땅",
    titleEn: "New Heaven and New Earth",
    dateLabel: "새 창조",
    rangeLabel: "요한계시록 21-22",
    summary: "하나님이 새 창조를 이루시고 친히 자기 백성과 함께 거하시며 모든 눈물을 닦으신다.",
    significance: "성경 타임라인은 임재의 완성과 새 창조로 끝나며, 창조의 처음 의도가 종말에 회복된다.",
    certainty: "B",
    mainPassages: ["요한계시록 21:1-5", "요한계시록 22:1-5"],
    keyPassages: ["요한계시록 21:3-5"],
    fulfillmentPassages: ["이사야 65:17", "베드로후서 3:13"],
    focusRefs: [nk("요한계시록", 21, 1, 21, 5), gr("요한계시록", "REV", 21, 1, 21, 5)],
    originalTerms: [ge("καινός", "kainos", "새로운", "요한계시록 21:1", "요한계시록 21:5")],
    controversyIds: ["C05"],
  },
];
